name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
        llvm: [19, 20]
    name: Build os=${{ matrix.os }} llvm=${{ matrix.llvm }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: vs-nix-overlay

      - name: Build
        run: nix build -L .#llvm_${{ matrix.llvm }}
